---
- name: Install ptp package
  apt:
    update_cache: yes
    name: linuxptp
    state: present
  tags: ptp

- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    masked: yes
    daemon_reload: yes
  tags: conf

- name: Create overlay directories
  file:
    path: '{{ item }}'
    state: directory
  with_items:
   - /etc/systemd/system/phc2sys.service.d/
   - /etc/systemd/system/ptp4l.service.d/
  tags: conf

- name: Deploy unit files
  template:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    mode: 0644
  with_items:
   - { src: 'phc2sys_mands.conf', dest: '/etc/systemd/system/phc2sys.service.d/phc2sys_mands.conf' }
   - { src: 'ptp_restart.conf', dest: '/etc/systemd/system/ptp4l.service.d/phc2sys.conf' }
  tags: conf

- name: Enable services
  systemd:
    name: '{{ item.name }}'
    state: restarted
    enabled: '{{ item.enabled }}'
    daemon_reload: yes
  with_items:
   - { name: phc2sys.service, enabled: yes }
   - { name: ptp4l.service, enabled: no }
   - { name: ptp4l.path, enabled: yes }
  tags: conf
